manifest:
  defaults:
    remote: urob
    revision: v0.3

  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

    - name: zmk-adaptive-key
      path: modules/zmk/adaptive-key

    - name: zmk-auto-layer
      path: modules/zmk/auto-layer

    - name: zmk-helpers
      path: modules/zmk/helpers

    - name: zmk-leader-key
      path: modules/zmk/leader-key

    - name: zmk-tri-state
      path: modules/zmk/tri-state

    - name: zmk-unicode
      path: modules/zmk/unicode

  self:
    path: config
